metaKeywords = "bradfield, vote, election, 2022, federal"
metaDescription = "Use your preferences to maximum effect in Bradfield this 2022 federal election!"
headerImagePath = "/img/lane-cove-river.jpg"
headerImageAlt = "View of the Lane Cove River"
headerImageWidth = "1632"
headerImageHeight = "612"
cloudflareWebAnalyticsToken = ""
footerText = """Authorised by Jeremy Epstein, Gordon, NSW.

Content and design copyleft 2022 [GreenAsh Services](https://greenash.net.au/).

In accordance with [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/).

Header image: [Reflections, Lane Cove River](https://commons.wikimedia.org/wiki/File:Reflections,_Lane_Cove_River.jpg), from Wikimedia Commons. [Icon from FreeSVG](https://freesvg.org/eco-tree-vector-icon).

[Source code on GitHub](https://github.com/Jaza/hackyourbradfieldvote)."""
